models/Buy.php
<?php

namespace app\models;

use Yii;
use yii\db\Query;
/**
 * This is the model class for table "buy".
 *
 * @property integer $id_buy
 * @property integer $id_company
 * @property integer $id_product
 * @property integer $id_partner
 * @property double $value_kurs_buy
 * @property string $name_product
 * @property string $date_buy
 * @property double $amount_buy
 * @property integer $id_unit
 * @property double $price_uah_buy
 * @property double $price_usd_buy
 * @property double $price_per_unit_usd_buy
 * @property double $price_per_unit_uah_buy
 * @property string $id_invoice
 * @property integer $is_fully_paid_buy
 * @property integer $is_fully_utilized_buy
 *
 * @property Company $idCompany
 * @property Product $idProduct
 * @property Partner $idPartner
 * @property Unit $idUnit
 * @property SpendBuy[] $spendBuys
 * @property UtilizedBuy[] $utilizedBuys
 */
class Buy extends \yii\db\ActiveRecord {

    /**
     * @inheritdoc
     */
    public static function tableName() {
        return 'buy';
    }

    /**
     * @inheritdoc
     */
    public function rules() {
        return [
            [['id_company', 'id_product', 'id_partner', 'id_unit', 'is_fully_paid_buy', 'is_fully_utilized_buy'], 'integer'],
            [['value_kurs_buy', 'amount_buy', 'price_uah_buy', 'price_usd_buy', 'price_per_unit_usd_buy', 'price_per_unit_uah_buy'], 'number'],
            [['date_buy'], 'safe'],
            [['name_product'], 'string', 'max' => 255],
            [['id_invoice'], 'string', 'max' => 100],
            [['id_company'], 'exist', 'skipOnError' => true, 'targetClass' => Company::className(), 'targetAttribute' => ['id_company' => 'id_company']],
            [['id_product'], 'exist', 'skipOnError' => true, 'targetClass' => Product::className(), 'targetAttribute' => ['id_product' => 'id_product']],
            [['id_partner'], 'exist', 'skipOnError' => true, 'targetClass' => Partner::className(), 'targetAttribute' => ['id_partner' => 'id_partner']],
            [['id_unit'], 'exist', 'skipOnError' => true, 'targetClass' => Unit::className(), 'targetAttribute' => ['id_unit' => 'id_unit']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels() {
        return [
            'id_buy' => 'ID покупки',
            'id_company' => 'Підприємство',
            'id_product' => 'Товар',
            'id_partner' => 'Партнер',
            'value_kurs_buy' => 'Курс грн/USD',
            'name_product' => 'Назва товару',
            'date_buy' => 'Дата покупки',
            'amount_buy' => 'Кількість товару',
            'id_unit' => 'Одиниця вимірювання',
            'price_uah_buy' => 'Ціна, грн',
            'price_usd_buy' => 'Ціна, USD',
            'price_per_unit_usd_buy' => 'Ціна за одницю, USD',
            'price_per_unit_uah_buy' => 'Ціна за одницю, грн',
            'id_invoice' => 'Накладна №',
            'is_fully_paid_buy' => 'Повністю оплачено',
            'is_fully_utilized_buy' => 'Повністю використано',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdCompany() {
        return $this->hasOne(Company::className(), ['id_company' => 'id_company']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdProduct() {
        return $this->hasOne(Product::className(), ['id_product' => 'id_product']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdPartner() {
        return $this->hasOne(Partner::className(), ['id_partner' => 'id_partner']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdUnit() {
        return $this->hasOne(Unit::className(), ['id_unit' => 'id_unit']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSpendBuys() {
        return $this->hasMany(SpendBuy::className(), ['id_buy' => 'id_buy']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUtilizedBuys() {
        return $this->hasMany(UtilizedBuy::className(), ['id_buy' => 'id_buy']);
    }

    public function autoPostFill() {
        if (!$this->date_buy) {
            $this->date_buy = date('Y-m-d');
        }

        if (!$this->price_per_unit_uah_buy && $this->price_uah_buy) {
            $this->price_per_unit_uah_buy = round($this->price_uah_buy / $this->amount_buy, 3);
        }

        if ($this->price_per_unit_uah_buy && !$this->price_uah_buy) {
            $this->price_uah_buy = round($this->price_per_unit_uah_buy * $this->amount_buy, 3);
        }

        if (!$this->name_product) {
            $saleProduct = Product::findOne($this->id_product);
            $this->name_product = $saleProduct->name_product;
        }

        $dateSaleKurs = Kurs::find()->where(['=', 'date_kurs', $this->date_buy])->one();
        $this->value_kurs_buy = $dateSaleKurs->value_kurs;
        $this->price_usd_buy = $dateSaleKurs->getUSDfromUAH($this->price_uah_buy);
        $this->price_per_unit_usd_buy = $dateSaleKurs->getUSDfromUAH($this->price_per_unit_uah_buy);
    }

    public function getRemainder() {
        $utilizations = $this->getUtilizedBuys()->all();
        $amount = $this->amount_buy;
        foreach ($utilizations as $utilization) {
            $amount -=$utilization->amount_utilized_buy;
        }
        return $amount;
    }

    public function getAvailableBuys($id_company, $id_partner) {
        $query = new Query;
        $query->select('buy.*, 
                        sum(spend_buy.amount_usd_spend_buy) as spendBuyPaid
                        ')
                ->from('buy')
                ->leftJoin('spend_buy', 'buy.id_buy=spend_buy.id_buy')
                ->where([
                    'and',
                    ['=', 'buy.id_company', $id_company],
                    ['=', 'buy.id_partner', $id_partner],
                    ['<>', 'buy.is_fully_paid_buy', 1],
                ])
                ->orderBy('buy.date_buy ASC')
                ->groupBy('buy.id_buy');
        return $query->all();
    }
    
}

controllers/BuyController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Buy;
use app\models\BuySearch;
use app\models\Kurs;
use app\models\Payment;
use yii\web\Controller;
use app\models\Company;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;

/**
 * BuyController implements the CRUD actions for Buy model.
 */
class BuyController extends Controller {

    /**
     * @inheritdoc
     */
    public function behaviors() {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Buy models.
     * @return mixed
     */
    public function actionIndex($id_company) {
        
        if (!Yii::$app->user->identity->is("admin|booker|operator=$id_company")) {
           throw new ForbiddenHttpException('Only admin, booker or company operator can see this page.');
        }

        $searchModel = new BuySearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        $dataProvider->query->andFilterWhere([ 'id_company' => $id_company,]);
        $company = Company::findOne($id_company);
        $partnerOptions = ArrayHelper::map($company->getPartners()->all(), 'id_partner', 'name_partner');
        $unitOptions = ArrayHelper::map($company->getUnits()->all(), 'id_unit', 'name_unit');
        return $this->render('index', [
                    'searchModel' => $searchModel,
                    'dataProvider' => $dataProvider,
                    'company' => $company,
                    'partnerOptions' => $partnerOptions,
                    'unitOptions' => $unitOptions,
        ]);
    }

    /**
     * Displays a single Buy model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id) {
        $model = $this->findModel($id);
        if (!Yii::$app->user->identity->is("admin|booker|operator={$model->id_company}")) {
           throw new ForbiddenHttpException('Only admin, booker or company operator can see this page.');
        }
        return $this->render('view', [
                    'model' => $model,
        ]);
    } 
    
    public function actionPayment($id) {
        $model = $this->findModel($id);
        if (!Yii::$app->user->identity->is("admin|booker|operator={$model->id_company}")) {
           throw new ForbiddenHttpException('Only admin, booker or company operator can see this page.');
        }
        $kurs = Kurs::find()->where(['=', 'date_kurs', date('Y-m-d')])->one();

        $payment = new Payment();
        $availablePayments = $payment->getAvailablePayments($model->id_company, $model->id_partner);
        return $this->render('payment', [
                    'model' => $model,
                    'availablePayments' => $availablePayments,
                    'kurs' => $kurs
        ]);
    }

    
    public function actionUsepayment($id_buy, $id_payment){
        
        $buy = Buy::findOne($id_buy);
        if (!Yii::$app->user->identity->is("admin|booker|operator={$buy->id_company}")) {
           throw new ForbiddenHttpException('Only admin, booker or company operator can see this page.');
        }
        
        $payment = new Payment();
        $payment->usePayment($id_buy, $id_payment);
        return $this->redirect(['payment', 'id' => $id_buy]);
    }
    /**
     * Creates a new Buy model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id_company) {
        if (!Yii::$app->user->identity->is("admin|booker|operator={$id_company}")) {
           throw new ForbiddenHttpException('Only admin, booker or company operator can see this page.');
        }
        
        $model = new Buy();
        $model->id_company = $id_company;
        if ($model->load(Yii::$app->request->post())) {
            // fill-in hidden fields
            $model->autoPostFill();
            if ($model->save()) {
                return $this->redirect(['view', 'id' => $model->id_buy]);
            }
        }
        $company = Company::findOne($id_company);
        return $this->render('create', [
                    'model' => $model,
                    'company' => $company
        ]);
    }

    /**
     * Updates an existing Buy model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id) {
        $model = $this->findModel($id);

        if (!Yii::$app->user->identity->is("admin|booker|operator={$model->id_company}")) {
           throw new ForbiddenHttpException('Only admin, booker or company operator can see this page.');
        }

        if ($model->load(Yii::$app->request->post())) {
            $model->autoPostFill();
            if($model->save()){
                return $this->redirect(['view', 'id' => $model->id_buy]);
            }
        } else {
            return $this->render('update', [
                        'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Buy model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id) {
        $model=$this->findModel($id);
        if (!Yii::$app->user->identity->is("admin|booker|operator={$model->id_company}")) {
           throw new ForbiddenHttpException('Only admin, booker or company operator can see this page.');
        }
        $id_company=$model->id_company;
        $model->delete();
        return $this->redirect(['index','id_company'=>$id_company]);
    }

    /**
     * Finds the Buy model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Buy the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id) {
        if (($model = Buy::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

}

views/buy/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\widgets\Select2;
use app\models\Product;
use app\models\Partner;
use app\models\Unit;

/* @var $this yii\web\View */
/* @var $model app\models\Buy */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="buy-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'id_company')->label('')->hiddenInput() ?>

    <?php
    echo $form->field($model, 'id_product')->widget(Select2::classname(), [
        'data' => Product::listAll($model->id_company),
        'showToggleAll' => false,
        'options' => ['placeholder' => 'Оберіть товар ...', 'multiple' => false],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>
    АБО
    <?= $form->field($model, 'name_product')->textInput(['maxlength' => true]) ?>

    <?php
    echo $form->field($model, 'id_partner')->widget(Select2::classname(), [
        'data' => Partner::listAll($model->id_company),
        'showToggleAll' => false,
        'options' => ['placeholder' => 'Оберіть партнера ...', 'multiple' => false],
        'pluginOptions' => [
            'allowClear' => true
        ],
    ]);
    ?>


    <div class="row">
        <div class="col-sm-3">
            <label class="control-label" for="buy-date_buy">Дата покупки</label>
            <?php
            echo yii\jui\DatePicker::widget([
                'model' => $model,
                'attribute' => 'date_buy',
                'language' => 'uk',
                'dateFormat' => 'yyyy-MM-dd',
                'options' => [
                    'class' => 'form-control'
                ]
            ]);
            ?>

        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'amount_buy')->textInput() ?>
        </div>
        <div class="col-sm-3">
            <?php
            echo $form->field($model, 'id_unit')->widget(Select2::classname(), [
                'data' => Unit::listAll($model->id_company),
                'showToggleAll' => false,
                'options' => ['placeholder' => 'Оберіть одиницю вимірювання ...', 'multiple' => false],
                'pluginOptions' => [
                    'allowClear' => true
                ],
            ]);
            ?>        </div>
        <div class="col-sm-3">
             <?= $form->field($model, 'id_invoice')->textInput(['maxlength' => true]) ?>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-3">
            <?= $form->field($model, 'price_uah_buy')->textInput() ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'price_per_unit_uah_buy')->textInput() ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'is_fully_paid_buy')->checkbox() ?>
        </div>
        <div class="col-sm-3">
            <?= $form->field($model, 'is_fully_utilized_buy')->checkbox() ?>
        </div>
    </div>




   







    


    

    

    <div class="form-group">
    <?= Html::submitButton($model->isNewRecord ? 'Створити' : 'Змінити', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

        <?php ActiveForm::end(); ?>

</div>

views/buy/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\BuySearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="buy-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id_buy') ?>

    <?= $form->field($model, 'id_company') ?>

    <?= $form->field($model, 'id_product') ?>

    <?= $form->field($model, 'id_partner') ?>

    <?= $form->field($model, 'value_kurs_buy') ?>

    <?php // echo $form->field($model, 'name_product') ?>

    <?php // echo $form->field($model, 'date_buy') ?>

    <?php // echo $form->field($model, 'amount_buy') ?>

    <?php // echo $form->field($model, 'id_unit') ?>

    <?php // echo $form->field($model, 'price_uah_buy') ?>

    <?php // echo $form->field($model, 'price_usd_buy') ?>

    <?php // echo $form->field($model, 'price_per_unit_usd_buy') ?>

    <?php // echo $form->field($model, 'price_per_unit_uah_buy') ?>

    <?php // echo $form->field($model, 'id_invoice') ?>

    <?php // echo $form->field($model, 'is_fully_paid_buy') ?>

    <?php // echo $form->field($model, 'is_fully_utilized_buy') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/buy/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Buy */

$this->title = 'Нова покупка';
$this->params['breadcrumbs'][] = ['label' => 'Підприємства', 'url' => ['/company/index']];
$this->params['breadcrumbs'][] = ['label' => $company->name_company, 'url' => ['/company/view', 'id'=>$company->id_company]];
$this->params['breadcrumbs'][] = ['label' => 'Покупки', 'url' => ['index', 'id_company'=>$company->id_company]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="buy-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/buy/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Buy */

$company=$model->idCompany;
$this->title = 'Змінити покупку: ' . $model->id_buy;
$this->params['breadcrumbs'][] = ['label' => 'Підприємства', 'url' => ['/company/index']];
$this->params['breadcrumbs'][] = ['label' => $company->name_company, 'url' => ['/company/view', 'id'=>$company->id_company]];
$this->params['breadcrumbs'][] = ['label' => 'Покупки', 'url' => ['index', 'id_company'=>$company->id_company]];
$this->params['breadcrumbs'][] = ['label' => 'Покупка: ' . $model->id_buy, 'url' => ['view', 'id' => $model->id_buy]];
$this->params['breadcrumbs'][] = 'Змінити';
?>
<div class="buy-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/buy/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

use app\models\UtilizedPlace;

/* @var $this yii\web\View */
/* @var $model app\models\Buy */

$company=$model->idCompany;
$payments=$model->getSpendBuys()->all();
$utilizations=$model->getUtilizedBuys()->all();

$this->title = 'Покупка '.$model->id_buy;
$this->params['breadcrumbs'][] = ['label' => 'Підприємства', 'url' => ['/company/index']];
$this->params['breadcrumbs'][] = ['label' => $company->name_company, 'url' => ['/company/view', 'id'=>$company->id_company]];
$this->params['breadcrumbs'][] = ['label' => 'Покупки', 'url' => ['index', 'id_company'=>$company->id_company]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="buy-view">

    <h1><?= Html::encode($this->title) ?>
        <?= Html::a('Змінити', ['update', 'id' => $model->id_buy], ['class' => 'btn btn-xs btn-primary']) ?>
        <?= Html::a('Використання', ['/utilized-buy/index', 'id_buy' => $model->id_buy], ['class' => 'btn btn-xs btn-primary']) ?>
        <?= Html::a('Платежі', ['/buy/payment', 'id' => $model->id_buy], ['class' => 'btn btn-xs btn-primary']) ?>
        <?= Html::a('Видалити', ['delete', 'id' => $model->id_buy], [
            'class' => 'btn btn-xs btn-danger',
            'data' => [
                'confirm' => 'Ви дійсно бажаєте видалити цей запис?',
                'method' => 'post',
            ],
        ]) ?>
   </h1>

<table id="w0" class="table table-striped table-bordered detail-view"><tbody>
    <tr><th>Товар</th>
        <td><?=( $model->id_product ? Html::a( $model->name_product, ['/product/view', 'id' => $model->id_product ]) : $model->name_product)?></td>
        <th>Партнер</th>
        <td><?=( $model->idPartner ? Html::a( "{$model->idPartner->name_partner} {$model->idPartner->kontakt_partner}", ['/partner/view', 'id' => $model->id_partner ]): '')?></td>
    </tr>
    <tr>
        <th>Кількість товару</th>
        <td><?=(  $model->amount_buy ."&nbsp;".( $model->idUnit ? ($model->idUnit->name_unit) : '') )?></td>
        <th>Дата покупки</th>
        <td><?=date('d.m.Y',strtotime($model->date_buy) )?></td>
    </tr>
    <tr>
        <th>Ціна, грн</th><td><?=round($model->price_uah_buy,2)?></td>
        <th>Ціна, USD</th><td><?=round($model->price_usd_buy,2)?></td>
    </tr>
    <tr>
        <th>Ціна за одиницю, грн</th><td><?=round($model->price_per_unit_uah_buy,2)?></td>
        <th>Ціна за одиницю, USD</th><td><?=round($model->price_per_unit_usd_buy,2)?></td>
    </tr>
    <tr>
        <th>Курс, грн/USD</th><td><?=round($model->value_kurs_buy,2)?></td>
        <th>Накладна №</th><td><?=$model->id_invoice?></td>
    </tr>
    <tr>
        <th>Повністю оплачено </th><td><?=($model->is_fully_paid_buy ? 'Так':'Ні' )?></td>
        <th>Повністю використано</th><td><?=($model->is_fully_utilized_buy ? 'Так':'Ні' )?></td>
    </tr>
</tbody></table>
    
    
    
    <?php
    /*
    = DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id_buy',
            //'id_company',
            //'id_product',
            //'id_partner',
            //'name_product',
            //            [
            //                'attribute' => 'id_partner',
            //                'label' =>'Партнер',
            //                'format'=>'html',
            //                'value' => ( $model->idPartner ? Html::a( "{$model->idPartner->name_partner} {$model->idPartner->kontakt_partner}", ['/partner/view', 'id' => $model->id_partner ]): ''),
            //            ],
            //            [
            //                'attribute' => 'name_product',
            //                'label' =>'Товар',
            //                'format'=>'html',
            //                'value' => ( $model->id_product ? Html::a( $model->name_product, ['/product/view', 'id' => $model->id_product ]) : $model->name_product),
            //            ],
            //            [
            //                'label' =>'Кількість товару',
            //                'format'=>'html',
            //                'value' => (  $model->amount_buy ."&nbsp;".( $model->idUnit ? ($model->idUnit->name_unit) : '') ),
            //            ],
            //            [
            //                'attribute' => 'date_buy',
            //                'label' =>'Дата покупки',
            //                'value' => date('d.m.Y',strtotime($model->date_buy) ),
            //            ],
            //            [
            //                'attribute' => 'price_uah_buy',
            //                'label' =>'Ціна, грн',
            //                'value' => round($model->price_uah_buy,2),
            //            ],
            //            [
            //                'attribute' => 'price_usd_buy',
            //                'label' =>'Ціна, USD',
            //                'value' => round($model->price_usd_buy,2),
            //            ],
            //            [
            //                'attribute' => 'price_per_unit_uah_buy',
            //                'label' =>'Ціна за одиницю, грн',
            //                'value' => round($model->price_per_unit_uah_buy,2),
            //            ],
            //            [
            //                'attribute' => 'price_per_unit_usd_buy',
            //                'label' =>'Ціна за одиницю, USD',
            //                'value' => round($model->price_per_unit_usd_buy,2),
            //            ],
            // 'id_unit',
            //            [
            //                'attribute' => 'value_kurs_buy',
            //                'label' =>'Курс, грн/USD',
            //                'value' => round($model->value_kurs_buy,2),
            //            ],     
            //            'id_invoice',
            [
                'attribute' => 'is_fully_paid_buy',
                'label' =>'Повністю оплачено ',
                'value' => ($model->is_fully_paid_buy ? 'Так':'Ні' ),
            ],            
            [
                'attribute' => 'is_fully_utilized_buy',
                'label' =>'Повністю використано',
                'value' => ($model->is_fully_utilized_buy ? 'Так':'Ні' ),
            ],
        ],
    ]) */
    ?>

    
    <div class="row">
        <div class="col-sm-6">
            <h4>Платежі</h4>
            <table class="table table-striped table-bordered">
            <?php
            foreach($payments as $payment){
                $pm=$payment->idPayment;
                ?>
                <tr>
                    <td><?= $pm->id_payment?></td>
                    <td><?= date('d.m.Y',strtotime($pm->date_payment))?></td>
                    <td><?= $payment->amount_grn_spend_buy?>&nbsp;грн</td>
                    <td><?= $payment->amount_usd_spend_buy ?>&nbsp;USD</td>
                    <td><?= $payment->value_kurs_spend_buy ?>&nbsp;грн/USD</td>
                </tr>
                <?php
                
                
                
            }
            ?>
            </table>
        </div>
        <div class="col-sm-6">
            <h4>Використання</h4>
            <table class="table table-striped table-bordered">
            <?php
            foreach($utilizations as $utilization){
                ?>
                <tr>
                    <td><?=date('d.m.Y',strtotime($utilization->date_utilized_buy))?></td>
                    <td><?=($utilization->amount_utilized_buy." ".$utilization->idBuy->idUnit->name_unit)?></td>
                    <td><?php
                    $place=$utilization->idUtilizedPlace;
                    echo "<div> {$place->name_utilized_place} {$place->address_utilized_place} {$place->notes_utilized_place} </div>";
                    
                    $places=[];
                    $id_utilized_place_parent=$place->id_utilized_place_parent;
                    while($id_utilized_place_parent && !in_array($id_utilized_place_parent, $places)){
                        $places[]=$id_utilized_place_parent;
                        $place=  UtilizedPlace::findOne($id_utilized_place_parent);
                        echo "<div>@ {$place->name_utilized_place} {$place->address_utilized_place} {$place->notes_utilized_place} </div>";
                        $id_utilized_place_parent=$place->id_utilized_place_parent;
                    }

                    ?></td>
                </tr>
                <?php
                //
                //
                //id_utilized_place
            }
            ?>
            </table>
        </div>
    </div>
    
    
</div>